apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: backend-monitor
    namespace: monitoring
spec:
    selector:
        matchLabels:
            app: backend
    endpoints:
        - port: http
          interval: 15s
