FROM node:18 AS build
WORKDIR /app

# Installer outils de build
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install --verbose

COPY . ./
CMD ["npm", "start"]

