FROM node:20

WORKDIR /app

# Copie les fichiers package.json depuis le dossier backend
COPY ../projet_devops_backend/package*.json ./
RUN npm install

# Copie tout le code backend
COPY ../projet_devops_backend/ ./

EXPOSE 3000
CMD ["npm", "start"]
