name: Build & Push Frontend

on:
    push:
        paths:
            - "projet_devops_frontend/**"
            - "dockerfiles/Dockerfile.frontend"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Login to ACR
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            - name: Build frontend image
              run: |
                  docker build -f dockerfiles/Dockerfile.frontend -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest frontend/

            - name: Push frontend image
              run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
