name: Build & Push Frontend

on:
    workflow_dispatch:
    #push:
    #paths:
    #- "projet_devops_frontend/**"
    #- "docker/Dockerfile.frontend"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Github Action
              uses: actions/checkout@v3

            - name: Login to ACR
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            - name: Build frontend image
              run: |
                  docker build -f docker/Dockerfile.frontend -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./projet_devops_frontend

            - name: Push frontend image
              run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
